### ISSUE TITLE
android 部分机型播放一些动画只回调onVideoStart()和onVideoRender()方法

### ISSUE THREAD

**Issue by MrHayden** [Tencent/vap#188]
# issue 模版

1. 问题描述（重现路径）用下面的MP4文件播放一下就可以复现，部分手机才会这样
2. 运行环境（手机型号，Android/iOS版本等）OPPO A92s 5G  型号：PDKM00 ， android 11版本
3. 相关日志
4. 播放错误的文件（可选）

# issue template

![SI(`3(836LB)SR 88`GSML7](https://user-images.githubusercontent.com/19620807/146165116-9ce91ef4-0481-4491-881e-b2f9867a1d08.png)
![}G$V79E25 PBGSRGCD28W0T](https://user-images.githubusercontent.com/19620807/146165169-0f05f2ab-03cd-4b60-b684-4f9cb63f0c9b.png)

https://user-images.githubusercontent.com/19620807/146165272-fc8a54a0-5f0a-43bc-89cd-d22db1547ca8.mp4

**Comment by XuXiaoMing123** [comment]
不知道是不是动画时间太短的问题，这个动画多加了一点帧数的话是会回调onVideoComplete()  ,onVideoDestroy()方法

**Comment by hexleo** [comment]
我这用的视频测试，是有完整回调的，你自己检查下带，是不是业务逻辑的时序问题。你可以把vap的完整日志发出来，你过滤AnimPlayer这个tag看看

**Comment by XuXiaoMing123** [comment]
我是用demo测试的，这个问题是和机型有关，目前我是只在这个手机上发现了





只回调onVideoStart方法，我再次调用play的话日志看的是还在运行------------------&nbsp;原始邮件&nbsp;------------------




发件人:                                                                                                                        "Tencent/vap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/vap] android 部分机型播放一些动画只回调onVideoStart()和onVideoRender()方法 (Issue #188)





 
我这用的视频测试，是有完整回调的，你自己检查下带，是不是业务逻辑的时序问题。你可以把vap的完整日志发出来，你过滤AnimPlayer这个tag看看
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XuXiaoMing123** [comment]
> 我这用的视频测试，是有完整回调的，你自己检查下带，是不是业务逻辑的时序问题。你可以把vap的完整日志发出来，你过滤AnimPlayer这个tag看看

![image](https://user-images.githubusercontent.com/19620807/146327295-07231b2d-5430-4681-95c2-153494867bca.png)
![image](https://user-images.githubusercontent.com/19620807/146327319-881f656f-572c-4259-bd3d-41bb2f1a9ab2.png)
这是手机信息和日志

**Comment by hexleo** [comment]
你的日志不完整，你可以直接贴文本的日志，销毁过程都没看到日志

**Comment by XuXiaoMing123** [comment]
调用play之后日志就只停留在那呀，而且当前是还在播放状态，其实是已经播放完了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/vap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/vap] android 部分机型播放一些动画只回调onVideoStart()和onVideoRender()方法 (Issue #188)





 
你的日志不完整，你可以直接贴文本的日志，销毁过程都没看到日志
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XuXiaoMing123** [comment]
![image](https://user-images.githubusercontent.com/19620807/146477190-9987afaf-37ef-4568-b392-847915198b4e.png)

**Comment by hexleo** [comment]
你把系统日志一起打印出来看看，是不是出现什么error日志了

**Comment by XuXiaoMing123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/vap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/vap] android 部分机型播放一些动画只回调onVideoStart()和onVideoRender()方法 (Issue #188)





 
你把系统日志一起打印出来看看，是不是出现什么error日志了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XuXiaoMing123** [comment]
你可以在云测真机上看看有没有这个机型的手机，我这边就这个手机是异常的，我手动调用stop方法可以结束。
![image](https://user-images.githubusercontent.com/19620807/146478733-20a8d61a-a008-4ea4-a371-67a8dffd2144.png)
